# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily' # weekdays

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      deps:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/example'
    schedule:
      interval: 'daily' # weekdays

    # Do not get one pull request per version bump. Instead get one pull request
    # bumping several dependency versions at once:
    groups:
      deps:
        patterns:
          - '*'
